---
abstract: ~
author:
  - 'okamura <default {at} example.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Casual-Groonga
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Capture::Tiny: 0.13
  JSON: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/okamuuu/Casual-Groonga.git
version: 0.01
